language: node_js
node_js: 
  - "8.11.1"

branches: 
  only: 
   - "master"

before_script: 
  - "npm install -g "firebase-tools"

script: 
  - "npm run build-prod"

after_success: 
  - "firebase deploy --token $FIREBASE_TOKEN --non-interactive"

notifications: 
  email: 
    on_failure: change
    on_success: change